### ISSUE TITLE
[ISSUE]Supported MySQL Versions

### ISSUE THREAD

**Issue by devendermishra** [cossacklabs/acra#694]
**Describe the query**
I want to know what are the supported versions of MySQL with acra-server in community edition?

**To Reproduce**
NA

**Expected behavior**
NA

**Acra configuration files**
NA

**Environment (please complete the following information):**
- Acra version: [e.g. 0.90.0]
- Database server and its version: MySQL
- Installed components:
   - [x] AcraServer

- Data-in-transit encryption between Acra and the client-side application:
   - [ ] TLS
   - [ ] AcraConnector
   - [x] no transport encryption
- Installation way:
   - [x] via Docker
   - [ ] via package manager

**Comment by Lagovas** [comment]
Sorry for so long response. We don't recommend to use Acra 0.90 version and I didn't tested it due to it uses old approach with secure session as transport and acra-connector as additional proxy between app and acra-server, that looks overcomplicated for modern deployments.
Our tests regularly test Acra with mysql [5.7.25](https://github.com/cossacklabs/acra/blob/master/.circleci/config.yml#L503) and [5.7.31](https://github.com/cossacklabs/acra/blob/master/.circleci/config.yml#L450). Additionally, I had tested with fresh 5.7 and 5.5 images from the docker hub with Acra 0.95.0 and transparent encryption/decryption works.

Unfortunately, Acra Community edition doesn't support properly mysql 8.X client's that use  [CLIENT_QUERY_ATTRIBUTES](https://dev.mysql.com/doc/dev/mysql-server/latest/group__group__cs__capabilities__flags.html#ga3cd12e9fd3901274e239881796e5219b) at the wire protocol level. Mysql's CLI tool `mysql` uses it. We plan to bring it to the community addition in the next year.

How to detect that mysql driver uses CLIENT_QUERY_ATTRIBUTE? You will see next log from the acra-server:
`acra-server_1           | time="2023-12-21T22:20:25Z" level=debug msg="ignoring error of non parsed sql statement" error="syntax error: unexpected LEX_ERROR at position 2 near '\x00'"`.

**Comment by devendermishra** [comment]
Thanks @Lagovas. I am using master branch (Commit: 3a65ebf206928f1eb69fe3177271632e4b56fb2f).
